name: Auto Commit Every Day at 8 AM IST

on:
  schedule:
    - cron: '30 2 * * *'  # Runs every day at 2:30 AM UTC (8:00 AM IST)
  workflow_dispatch:      # Allow manual trigger too

jobs:
  commit-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance

    - name: Configure Git
      run: |
        git config --global user.name "Abizer Masavi"
        git config --global user.email "abizermasavi@gmail.com"

    - name: Run Auto-Commit Script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python3 script.py
